# FROM node:latest

# # Diretório de trabalho dentro do container
# WORKDIR /app

# # Copia apenas os arquivos de dependências primeiro (cache mais eficiente)
# COPY package*.json ./

# # Instala dependências
# RUN npm install

# # Copia o restante do projeto
# COPY . .

# # Compila o projeto (necessário para produção)
# RUN npm run build

# # Porta padrão do Medusa
# EXPOSE 9000

# # Comando para iniciar o servidor
# CMD ["npm", "run", "start"]

FROM node:23 as builder

WORKDIR /app/dsilva-store

COPY . . 

RUN rm -rf node_modules

RUN apt-get update && apt-get install -y python3 python3-pip python-is-python3

RUN yarn install --loglevel=error

RUN yarn run build


FROM node:23

# Bug https://github.com/coollabsio/coolify/issues/1930
ARG COOKIE_SECRET
ARG JWT_SECRET
ARG STORE_CORS
ARG ADMIN_CORS
ARG AUTH_CORS
ARG DISABLE_ADMIN
ARG WORKER_MODE
ARG PORT
ARG DATABASE_URL
ARG REDIS_URL
ARG BACKEND_URL

RUN echo "${PORT}"

WORKDIR /app/dsilva-store

RUN mkdir .dsilva-store

# COPY package*.json .yarnrc.yml yarn.lock ./ 

# COPY medusa-config.ts .
# COPY tsconfig.json .

RUN apt-get update && apt-get install -y python3 python3-pip python-is-python3

COPY --from=builder /app/dsilva-store/.dsilva-store ./.dsilva-store

WORKDIR /app/dsilva-store/.dsilva-store/server

RUN yarn install --production


# RUN medusa migrations run 
COPY migrations.sh /app/dsilva-store/.dsilva-store/server/migrations.sh
RUN chmod +x /app/dsilva-store/.dsilva-store/server/migrations.sh
RUN /app/dsilva-store/.dsilva-store/server/migrations.sh

RUN rm /app/dsilva-store/.dsilva-store/server/migrations.sh

CMD ["yarn", "run", "start"]